// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/cli/v1/cli.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCliSecretRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SessionPublicKey    string                 `protobuf:"bytes,1,opt,name=session_public_key,json=sessionPublicKey,proto3" json:"session_public_key,omitempty"`
	SecretName          string                 `protobuf:"bytes,2,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	SecretVersionNumber *int32                 `protobuf:"varint,3,opt,name=secret_version_number,json=secretVersionNumber,proto3,oneof" json:"secret_version_number,omitempty"`
	WorkspaceId         string                 `protobuf:"bytes,4,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	OrganizationId      string                 `protobuf:"bytes,5,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetCliSecretRequest) Reset() {
	*x = GetCliSecretRequest{}
	mi := &file_api_proto_cli_v1_cli_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCliSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCliSecretRequest) ProtoMessage() {}

func (x *GetCliSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cli_v1_cli_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCliSecretRequest.ProtoReflect.Descriptor instead.
func (*GetCliSecretRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cli_v1_cli_proto_rawDescGZIP(), []int{0}
}

func (x *GetCliSecretRequest) GetSessionPublicKey() string {
	if x != nil {
		return x.SessionPublicKey
	}
	return ""
}

func (x *GetCliSecretRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *GetCliSecretRequest) GetSecretVersionNumber() int32 {
	if x != nil && x.SecretVersionNumber != nil {
		return *x.SecretVersionNumber
	}
	return 0
}

func (x *GetCliSecretRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *GetCliSecretRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type GetCliSecretResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EncryptedBlob     []byte                 `protobuf:"bytes,1,opt,name=encrypted_blob,json=encryptedBlob,proto3" json:"encrypted_blob,omitempty"`
	SessionWrappedKey []byte                 `protobuf:"bytes,2,opt,name=session_wrapped_key,json=sessionWrappedKey,proto3" json:"session_wrapped_key,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetCliSecretResponse) Reset() {
	*x = GetCliSecretResponse{}
	mi := &file_api_proto_cli_v1_cli_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCliSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCliSecretResponse) ProtoMessage() {}

func (x *GetCliSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cli_v1_cli_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCliSecretResponse.ProtoReflect.Descriptor instead.
func (*GetCliSecretResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cli_v1_cli_proto_rawDescGZIP(), []int{1}
}

func (x *GetCliSecretResponse) GetEncryptedBlob() []byte {
	if x != nil {
		return x.EncryptedBlob
	}
	return nil
}

func (x *GetCliSecretResponse) GetSessionWrappedKey() []byte {
	if x != nil {
		return x.SessionWrappedKey
	}
	return nil
}

var File_api_proto_cli_v1_cli_proto protoreflect.FileDescriptor

const file_api_proto_cli_v1_cli_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/cli/v1/cli.proto\x12\x06cli.v1\"\x83\x02\n" +
	"\x13GetCliSecretRequest\x12,\n" +
	"\x12session_public_key\x18\x01 \x01(\tR\x10sessionPublicKey\x12\x1f\n" +
	"\vsecret_name\x18\x02 \x01(\tR\n" +
	"secretName\x127\n" +
	"\x15secret_version_number\x18\x03 \x01(\x05H\x00R\x13secretVersionNumber\x88\x01\x01\x12!\n" +
	"\fworkspace_id\x18\x04 \x01(\tR\vworkspaceId\x12'\n" +
	"\x0forganization_id\x18\x05 \x01(\tR\x0eorganizationIdB\x18\n" +
	"\x16_secret_version_number\"m\n" +
	"\x14GetCliSecretResponse\x12%\n" +
	"\x0eencrypted_blob\x18\x01 \x01(\fR\rencryptedBlob\x12.\n" +
	"\x13session_wrapped_key\x18\x02 \x01(\fR\x11sessionWrappedKey2_\n" +
	"\n" +
	"CliService\x12Q\n" +
	"\x14GetSecretVersionData\x12\x1b.cli.v1.GetCliSecretRequest\x1a\x1c.cli.v1.GetCliSecretResponseBJ\n" +
	"\x13io.ennote.cli.protoP\x01Z1github.com/ennote-io/ennote-cli/internal/grpc/pbb\x06proto3"

var (
	file_api_proto_cli_v1_cli_proto_rawDescOnce sync.Once
	file_api_proto_cli_v1_cli_proto_rawDescData []byte
)

func file_api_proto_cli_v1_cli_proto_rawDescGZIP() []byte {
	file_api_proto_cli_v1_cli_proto_rawDescOnce.Do(func() {
		file_api_proto_cli_v1_cli_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_cli_v1_cli_proto_rawDesc), len(file_api_proto_cli_v1_cli_proto_rawDesc)))
	})
	return file_api_proto_cli_v1_cli_proto_rawDescData
}

var file_api_proto_cli_v1_cli_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_cli_v1_cli_proto_goTypes = []any{
	(*GetCliSecretRequest)(nil),  // 0: cli.v1.GetCliSecretRequest
	(*GetCliSecretResponse)(nil), // 1: cli.v1.GetCliSecretResponse
}
var file_api_proto_cli_v1_cli_proto_depIdxs = []int32{
	0, // 0: cli.v1.CliService.GetSecretVersionData:input_type -> cli.v1.GetCliSecretRequest
	1, // 1: cli.v1.CliService.GetSecretVersionData:output_type -> cli.v1.GetCliSecretResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_cli_v1_cli_proto_init() }
func file_api_proto_cli_v1_cli_proto_init() {
	if File_api_proto_cli_v1_cli_proto != nil {
		return
	}
	file_api_proto_cli_v1_cli_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cli_v1_cli_proto_rawDesc), len(file_api_proto_cli_v1_cli_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_cli_v1_cli_proto_goTypes,
		DependencyIndexes: file_api_proto_cli_v1_cli_proto_depIdxs,
		MessageInfos:      file_api_proto_cli_v1_cli_proto_msgTypes,
	}.Build()
	File_api_proto_cli_v1_cli_proto = out.File
	file_api_proto_cli_v1_cli_proto_goTypes = nil
	file_api_proto_cli_v1_cli_proto_depIdxs = nil
}
